run on terminal
# pip install numpy matplotlib

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

- create
- basic operation
- math operation
- indexing and slicing
- boolean filter

In [ ]:
x = np.array([1,2,3,4,5])
print(x)
print(x.shape)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,9,9]])
print(b)
print(b.shape)

In [ ]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

- random
- arange
- linspace

In [ ]:
np.random.rand(3,3)

In [ ]:
r1 = np.random.randint(-5,6, (5,5))
print(r1)

In [ ]:
# start, stop, gap
np.arange(0,50, .5)

In [ ]:
# start, stop, number_of_item
np.linspace(0, 50, 10)

array attributes
- shape
- dtype
- ndim
- size

basic operations
- sum
- mean
- min
- max
- std
- reshape
- transpose
- flatten

In [ ]:
x.dtype

In [ ]:
x = np.random.rand(3,3)
x.dtype

In [ ]:
x.ndim

In [ ]:
z = np.random.randint(1,5, (3,3,3))
z.ndim

In [ ]:
z.size

In [ ]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0)) # column-wise
print(a.sum(axis=1)) # row-wise

print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())
# all the methods can be used with axis

In [ ]:
z = np.random.randint(11,99, (5,5))
print(z)
print('transpose')
print(z.transpose()) # or print(z.T)
print('flattened')
print(z.flatten())

In [ ]:
a = np.random.randint(1,10, (4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(2,10))
print(a.reshape(10,2))
# print(a.reshape(5,2,2))

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,2],[6,3]])
print(a)
print(b)

In [ ]:
# when using 2 matrix, the shape must be the same
print(a + b)
print(a - b) 
print(a / b) # element-wise division
print(a * b) # element-wise multiplication
print(a @ b) # matrix multiplication
print(a.dot(b)) # matrix multiplication

In [ ]:
# when using matrix and scalar
print(a - 10) # broadcasting
print(a * 10) # broadcasting
print(a / 10) # broadcasting
print(a + 10) # broadcasting

In [81]:
# indexing
print(a[0,0])
print(a[-1,-1])

1
4


In [83]:
# slicing
x = np.random.randint(1,10, (5,5))
print(x)
print(x[:,0]) # first column
print(x[:,-1]) # last column
print(x[:,:3]) # first 3 columns

[[4 3 4 1 6]
 [3 3 5 7 5]
 [9 3 2 6 7]
 [4 7 2 4 5]
 [4 3 5 4 7]]
[4 3 9 4 4]
[6 5 7 5 7]
[[4 3 4]
 [3 3 5]
 [9 3 2]
 [4 7 2]
 [4 3 5]]
